version: '2'
services:
  task-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/task/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=task
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
